version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: verification_db
    environment:
      POSTGRES_DB: verificationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anonymous67
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: verification_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/verificationdb
      DB_USERNAME: postgres
      DB_PASSWORD: Anonymous67
      JWT_SECRET: mySecretKeyHereMakeItLongEnough123456
      ADMIN_EMAIL: bilalidris011@gmail.com
      ADMIN_PASSWORD: Anonymous67
      ADMIN_USERNAME: System Admin
    depends_on:
      - postgres

volumes:
  postgres_data: