spring:
  application:
    name: UserVerification

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/verificationdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Anonymous67}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyHereMakeItLongEnough123456}
  expiration: 86400000

admin:
  email: ${ADMIN_EMAIL:bilalidris011@gmail.com}
  password: ${ADMIN_PASSWORD:Anonymous67}
  username: ${ADMIN_USERNAME:System Admin}

server:
  port: 8080